### ISSUE TITLE
how to use path & demo doesn't seems to be working

### ISSUE THREAD

**Issue by prakash** [MrAnchovy/Kohana_Smarty3#11]
the demo doesn't seems to be working at `/smarty/smartydemo`

`127             throw new SmartyException("Unable to load template {$_template->source->type} '{$_template->source->name}'{$parent_resource}");`

also how can I include css/images/js ?
below is my structure and I want to include my assets (css or js or images) on index.tpl or core.tpl
I also want to know how can I attach images in my style.css

```
| default
    | assets
        | js
            script.js
        | css
            - style.css
        | images
            - logo.png
    | elements
    | layouts
        - core.tl
    - index.tpl
```

I tried with different combinations but it doesn't seems to be working at all.

**Comment by MrAnchovy** [comment]
Sorry, 0.9.4 was broken (`views` directory in modules was not searched for a template) - update to HEAD

Paths to images (and css/js files) need to be hard coded. Asset handling is not within the scope of a template engine, but it is very much part of a theme engine which I will be releasing today (supporting Smarty of course).

**Comment by prakash** [comment]
thx, I am eager to see and use what you have in the new theme engine.
