### ISSUE TITLE
Kohana Route engine available.

### ISSUE THREAD

**Issue by Fedcomp** [MrAnchovy/Kohana_Smarty3#13]
This module seems not available access to kohana route engine.
What i mean?
in-template access to make route paths

**bootstrap.php**

``` php
Route::set('default', '(<controller>(/<action>(/<id>)))')
    ->defaults(array(
        'controller' => 'main',
        'action'     => 'index',
    ));
```

**somewhere in .tpl**
`{route name='default' controller='somecontroller' action='notindex'}`

can you add this? it will be very usefull.

**Comment by MrAnchovy** [comment]
This is exactly the opposite of why we have template engines - templates are only concerned with presenting information that is provided to them by a controller. Templates must NOT decide for themselves that they want some information and go and get it.
