### ISSUE TITLE
Make it work with Kohana 3.3

### ISSUE THREAD

**Issue by MrAnchovy** [MrAnchovy/Kohana_Smarty3#17]
The change to Initial_Capitals in the new class auto-loader is a pain. Not sure what else is broken.

**Comment by seyfer** [comment]
Try use it with Kohana 3.3 - template not found. Always go to standart View::factory() function, not to Smarty module directory.

**Comment by samuelecarpene** [comment]
To make it work you must do this:
rename files and folder with the first letter capitalized
The files to rename are these:
- classes/kohana -> classes/Kohana
- classes/kohana/smarty -> classes/Kohana/Smarty
- classes/kohana/smarty/helper.php -> classes/Kohana/Smarty/Helper.php
- classes/smarty-> classes/Smarty
- classes/smarty/helper.php-> classes/Smarty/Helper.php
- classes/smarty/view.php-> classes/Smarty/View.php

This solve the 3.3 compatibility.
I hope  MrAnchovy add this to the master version.
Bye.

**Comment by MrAnchovy** [comment]
Done some time ago
