### ISSUE TITLE
unable to use smarty {extends}

### ISSUE THREAD

**Issue by prakash** [MrAnchovy/Kohana_Smarty3#6]
while using {extends} tags on tpl file I am getting an exception error

```throw new SmartyException("Unable to read template {$this->resource_type} '{$this->resource_name}'");

```
```

**Comment by MrAnchovy** [comment]
Are all your template files in `APPPATH.views`? If they are in a module's `views` directory there seems to me some inconsistency as to whether it works or not (and it shouldn't work at all!). For now, is putting all the view files in directories off `APPPATH.views` an acceptable workaround? Or you could bypass Kohana views altogether, get hold of a Smarty object with `View::smarty()` and use absolute paths? Global view variables should still be visible.

But I will fix it some day...

**Comment by prakash** [comment]
yes below is my application views structure

<pre>
application/views/
    - default
        - layouts
            - core.tpl
        - index.tpl
</pre>


in core.tpl I have following code as a placeholder

<pre>
{block name="content"}{/block}
</pre>


and in index.tpl

<pre>
{extends file="layouts/core.tpl"}

{block name="content"}
    if you can view it, then it's working :)
{/block}
</pre>


and finally, the error:
```throw new SmartyException("Unable to read template {$this->resource_type} '{$this->resource_name}'");

```
```

**Comment by MrAnchovy** [comment]
I think you want

```
{extends file="default/layouts/core.tpl"}
```

because include/extends paths are relative to the (array of) paths in $_template_path, not relative to the current template.

I have just pushed a fix that correctly adds the module paths so {include}d and {extend}ed templates should be found  in any `views` directory (as long as you have the path within the directory correct! :D

**Comment by prakash** [comment]
so is this fix in addition with supporting latest smarty version included on master?

**Comment by MrAnchovy** [comment]
Yes it is, and tagged 0.9.4
