### ISSUE TITLE
I can't update smarty core library

### ISSUE THREAD

**Issue by prakash** [MrAnchovy/Kohana_Smarty3#7]
The smarty version you are using on your module is Smarty 3.0.8 and when trying to replace the library to the latest one it does not work and produce errors. Isn't it possible to update the ore library?

**Comment by MrAnchovy** [comment]
In most cases it has been a simple drop-in replacement but I have stayed away from the recent releases - 5 releases in a month does not give me a lot of confidence.

It [[http://smarty-php.googlecode.com/svn/trunk/distribution/change_log.txt | does seem to have slowed down]] a bit now though, so I will give it a try.

**Comment by MrAnchovy** [comment]
Now [fixed](https://github.com/MrAnchovy/Kohana_Smarty3/commit/bd081713d09368d861fac81b0599a6b6f961c978). There were a few things that have changed (for the better) in Smarty 2.1 that broke the workarounds I had to put in the 3.0 integration!
